name: fed-stackfpad
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - cloudpickle=3.0.0=py38h06a4308_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - hyperopt=0.2.7=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxgboost=1.4.0=h9c3ff4c_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpld3=0.5.9=py38h06a4308_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - py-xgboost=1.4.0=py38h578d9bd_0
  - py4j=0.10.9.7=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - readline=8.1=h27cfd23_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - xgboost=1.4.0=py38h578d9bd_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - absl-py==1.0.0
      - alembic==1.14.1
      - anyio==3.7.1
      - argon2-cffi==21.1.0
      - argparse==1.4.0
      - attrs==21.2.0
      - babel==2.9.1
      - backcall==0.2.0
      - bayesian-optimization==1.4.3
      - beautifulsoup4==4.10.0
      - bidict==0.23.1
      - bleach==4.1.0
      - blinker==1.8.2
      - blobfile==1.2.5
      - cachetools==4.2.4
      - cffi==1.15.0
      - charset-normalizer==2.0.7
      - click==8.1.7
      - cmasher==1.6.3
      - colorama==0.4.6
      - colorlog==6.9.0
      - colorspacious==1.1.2
      - cryptography==39.0.0
      - cycler==0.10.0
      - dall-e==0.1
      - debugpy==1.5.0
      - decorator==5.1.0
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - e13tools==0.9.6
      - einops==0.3.2
      - entrypoints==0.3
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - filelock==3.3.0
      - flask==3.0.3
      - flask-socketio==5.3.6
      - fsspec==2024.3.1
      - ftfy==6.2.3
      - future==0.18.2
      - gdown==4.6.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - greenlet==3.1.1
      - grpcio==1.43.0
      - h11==0.14.0
      - httplib2==0.21.0
      - huggingface-hub==0.12.1
      - idna==3.3
      - imageio==2.13.5
      - importlib-metadata==4.10.0
      - importlib-resources==6.4.5
      - iniconfig==1.1.1
      - ipykernel==6.4.1
      - ipython==7.28.0
      - ipython-genutils==0.2.0
      - itsdangerous==2.2.0
      - jedi==0.18.0
      - jeepney==0.8.0
      - joblib==1.1.0
      - json5==0.9.6
      - jsonschema==4.1.0
      - jupyter-client==7.0.6
      - jupyter-core==4.8.1
      - jupyter-server==1.11.1
      - jupyterlab==3.2.0
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.8.2
      - kiwisolver==1.3.2
      - mako==1.3.9
      - markdown==3.3.6
      - markupsafe==2.1.5
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - mpmath==1.3.0
      - mypy==0.910
      - mypy-extensions==0.4.3
      - nbclassic==0.3.2
      - nbclient==0.5.4
      - nbconvert==6.2.0
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - networkx==2.6.3
      - ninja==1.10.2.2
      - notebook==6.4.4
      - numpy==1.21.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn==8.2.0.51
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - nvidia-pyindex==1.0.9
      - oauthlib==3.1.1
      - opencv-python==4.5.5.62
      - openpyxl==3.0.9
      - optuna==4.2.0
      - packaging==21.0
      - pandas==1.4.2
      - pandocfilters==1.5.0
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - platformdirs==4.2.2
      - plotly==5.7.0
      - pluggy==1.0.0
      - prometheus-client==0.11.0
      - prompt-toolkit==3.0.20
      - protobuf==3.18.1
      - psutil==5.8.0
      - ptyprocess==0.7.0
      - py==1.10.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.20
      - pycryptodomex==3.11.0
      - pydicom==2.2.2
      - pygments==2.10.0
      - pyparsing==2.4.7
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyrsistent==0.18.0
      - pysocks==1.7.1
      - pytest==6.2.5
      - python-dateutil==2.8.2
      - python-engineio==4.9.1
      - python-gdcm==3.0.10.2
      - python-slugify==5.0.2
      - python-socketio==5.11.3
      - pytz==2021.3
      - pywavelets==1.2.0
      - pyyaml==6.0
      - pyzmq==22.3.0
      - regex==2024.11.6
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - requests-unixsocket==0.2.0
      - rsa==4.8
      - safetensors==0.4.3
      - scikit-image==0.19.1
      - scipy==1.7.1
      - seaborn==0.11.2
      - secretstorage==3.3.3
      - send2trash==1.8.0
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - setuptools==59.6.0
      - simple-websocket==1.0.0
      - sklearn==0.0
      - smmap==5.0.1
      - sniffio==1.2.0
      - soupsieve==2.3.1
      - sqlalchemy==2.0.38
      - sympy==1.12
      - tenacity==8.0.1
      - tensorboard==2.7.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==1.8
      - terminado==0.12.1
      - testpath==0.5.0
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.5.4
      - toml==0.10.2
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchinfo==1.8.0
      - torchvision==0.17.2
      - tornado==6.1
      - tqdm==4.62.3
      - traitlets==5.1.0
      - triton==2.2.0
      - typing-extensions==4.11.0
      - uritemplate==4.1.1
      - urllib3==1.26.18
      - versioneer==0.28
      - wandb==0.17.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.2.1
      - werkzeug==3.0.3
      - wheel==0.37.1
      - wsproto==1.2.0
      - xmltodict==0.12.0
      - zipp==3.7.0
prefix: /home/mgundogar/miniconda3/envs/fed-stackfpad
